"""improve api_keys schema

Revision ID: a64773202922
Revises: 533c5eb62cb4
Create Date: 2026-07-26 21:30:43.195791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64773202922'
down_revision: Union[str, Sequence[str], None] = '533c5eb62cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('secret_key_hash', sa.String(length=255), nullable=False))
    op.add_column('api_keys', sa.Column('environment', sa.String(length=10), nullable=False))
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('api_keys_secret_key_key'), 'api_keys', type_='unique')
    op.drop_constraint(op.f('api_keys_merchant_id_fkey'), 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'merchants', ['merchant_id'], ['id'], ondelete='CASCADE')
    op.drop_column('api_keys', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('secret_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('api_keys_merchant_id_fkey'), 'api_keys', 'merchants', ['merchant_id'], ['id'])
    op.create_unique_constraint(op.f('api_keys_secret_key_key'), 'api_keys', ['secret_key'])
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'environment')
    op.drop_column('api_keys', 'secret_key_hash')
    # ### end Alembic commands ###
